name: Python application

on:
  push:
    branches: [ "main", "dev-GuCATs" ]
  pull_request:
    branches: [ "main", "dev-GuCATs" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        architecture: [ x64, arm64 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build exe
      run: |
        ./build.bat ${{ matrix.architecture }}

    - name: Compress build
      run: |
        Compress-Archive -Path ./dist/* -DestinationPath ./dist_${{ matrix.architecture }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSPCManagerHelper_Beta_${{ matrix.os }}_${{ matrix.architecture }}
        path: ./dist_${{ matrix.architecture }}.zip
